name: Build and Package on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller -F -w --name gb688 --icon=pdf.ico pdf_export.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-exe
          path: dist/
